# Template: /usr/share/doc/alacritty/example/alacritty.yml

window:
  dimensions:
    columns: 80
    lines: 24
  decorations: none
  startup_mode: Maximized
  gtk_theme_variant: dark

# Font configuration
font:
  normal:
    family: Source Code Pro
    style: Regular

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  bold_italic:
    family: Source Code Pro
    style: Bold Italic

  size: 11.0

draw_bold_text_with_bright_colors: true

# Color Theme (Tomorrow night bright + VS Code)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#eaeaea'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#d54e53'
    green:   '#23d18b'
    yellow:  '#e6c547'
    blue:    '#3b8eea'
    magenta: '#c397d8'
    cyan:    '#70c0ba'
    white:   '#e5e5e5'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#0dbc79'
    yellow:  '#e7c547'
    blue:    '#2472c8'
    magenta: '#b77ee0'
    cyan:    '#29b8db'
    white:   '#e5e5e5'

  # Selection
  selection:
    text: CellBackground
    background: CellForeground

# Background opacity
background_opacity: 0.75

selection:
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

# Shell
shell:
  program: /usr/bin/zsh
  # args:
  #   - --login
  #   - -c
  #   - tmux

# Mouse bindings
mouse:
  url:
    launcher:
      program: xdg-open
      args: []

# Key bindings
key_bindings:
  - { key: V,		mods: Control|Shift,	action: Paste            }
  - { key: C,		mods: Control|Shift,	action: Copy             }
  - { key: Key0,	mods: Control,		action: ResetFontSize    }
  - { key: Colon,	mods: Control,		action: IncreaseFontSize }
  - { key: Semicolon,	mods: Control,		action: DecreaseFontSize }
  - { key: N,		mods: Control|Shift,	action: SpawnNewInstance }
